class_name BoardSounds
extends Node
## The sounds a turn makes.
##
## One player per sound rather than one shared player, so a take that triggers
## hot dice can ring both at once instead of cutting the first one off — which
## is exactly the moment worth hearing.
##
## Everything routes through the SFX bus, so the options menu's existing volume
## slider governs it with no extra wiring.
##
## The sounds themselves are generated by tools/generate_sfx.gd. They are
## ordinary .wav assets, replaceable one at a time by anything better without a
## code change.

const BUS := &"SFX"
const SFX_DIR := "res://assets/sfx"

## Above this share of a turn's expected worth, a take gets the big sound. A
## take should not sound triumphant just because a level's numbers are large,
## so the threshold is relative and never absolute.
const BIG_TAKE_RATIO := 0.5

var _players : Dictionary = {}

func _ready() -> void:
	for name in ["take", "take_big", "hot_dice", "bank", "farkle", "roll"]:
		_players[name] = _build_player(name)

func _build_player(name : String) -> AudioStreamPlayer:
	var path := "%s/%s.wav" % [SFX_DIR, name]
	if not ResourceLoader.exists(path):
		# A missing sound is not worth crashing a level over. Run
		# tools/generate_sfx.gd to put them back.
		push_warning("missing sound %s" % path)
		return null
	var player := AudioStreamPlayer.new()
	player.stream = load(path)
	player.bus = BUS
	add_child(player)
	return player

func play(name : String, pitch : float = 1.0) -> void:
	var player : AudioStreamPlayer = _players.get(name, null)
	if player == null:
		return
	player.pitch_scale = pitch
	player.play()

func play_roll() -> void:
	# A little pitch variation, so six rolls in a row do not sound like one
	# sample being retriggered — which is what they are.
	play("roll", randf_range(0.94, 1.08))

## Picks the take sound by how big the take was against what one turn of this
## level is expected to be worth, and pitches it up with the combo so a run of
## takes climbs rather than repeating.
func play_take(points : int, expected_per_turn : float, combo_count : int) -> void:
	var share := points / maxf(1.0, expected_per_turn)
	var pitch := clampf(1.0 + float(maxi(0, combo_count - 1)) * 0.06, 1.0, 1.4)
	play("take_big" if share >= BIG_TAKE_RATIO else "take", pitch)

func play_hot_dice() -> void:
	play("hot_dice")

func play_bank() -> void:
	play("bank")

func play_farkle() -> void:
	play("farkle")
